// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Z1bDddEpZv9SIK-qhSOokIFKLGKFncA',
    appId: '1:80703563381:web:ab394fb0e0ca03d2913a3c',
    messagingSenderId: '80703563381',
    projectId: 'prestasiku-8540b',
    authDomain: 'prestasiku-8540b.firebaseapp.com',
    storageBucket: 'prestasiku-8540b.appspot.com',
    measurementId: 'G-45PKGCMFF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQf4Wd4mWEejwv7KMlUE4SX7jdl4w5Lhk',
    appId: '1:80703563381:android:9b1f330a321f4531913a3c',
    messagingSenderId: '80703563381',
    projectId: 'prestasiku-8540b',
    storageBucket: 'prestasiku-8540b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgNKsWezjnxxpehy6QVJi3jSlO6XBDgI',
    appId: '1:80703563381:ios:fc4628ae0213e128913a3c',
    messagingSenderId: '80703563381',
    projectId: 'prestasiku-8540b',
    storageBucket: 'prestasiku-8540b.appspot.com',
    iosBundleId: 'com.example.prestasiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgNKsWezjnxxpehy6QVJi3jSlO6XBDgI',
    appId: '1:80703563381:ios:2e1dc7718ca4ea31913a3c',
    messagingSenderId: '80703563381',
    projectId: 'prestasiku-8540b',
    storageBucket: 'prestasiku-8540b.appspot.com',
    iosBundleId: 'com.example.prestasiku.RunnerTests',
  );
}
